#include <iostream>
#include <memory>
#include <string>

// gRPC headers
#include <grpcpp/grpcpp.h>

// These headers are generated by the protoc command we discussed
#include "./rpc_gen/signaling.grpc.pb.h"

using grpc::Server;
using grpc::ServerBuilder;
using grpc::ServerContext;
using grpc::Status;

// These namespaces come from your .proto file
using signaling::MediaSignaling;
using signaling::CallRequest;
using signaling::CallResponse;

// 1. Logic Implementation Class
class MediaSignalingImpl final : public MediaSignaling::Service {
    
    // This function runs whenever Django calls 'InitiateCall'
    Status InitiateCall(ServerContext* context, const CallRequest* request,
                       CallResponse* reply) override {
        
        // Extract data from the request (Note: room_id is now a string)
        std::string room = request->room_id();
        std::string user = request->user_id();

        std::cout << "📞 [C++ Server] Received Call Request!" << std::endl;
        std::cout << "🏠 Room ID: " << room << std::endl;
        std::cout << "👤 User ID: " << user << std::endl;

        // MOCK LOGIC: In the future, this is where WebRTC starts.
        // For now, we just send a success message back to Django.
        reply->set_success(true);
        reply->set_sdp_answer("v=0\no=- 4321 5678 IN IP4 127.0.0.1..."); // Dummy SDP
        
        return Status::OK;
    }
};

// 2. Server Runner
void RunServer() {
    std::string server_address("0.0.0.0:50051");
    MediaSignalingImpl service;

    ServerBuilder builder;
    // Listen on port 50051 without SSL (Insecure) for local development
    builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
    builder.RegisterService(&service);

    std::unique_ptr<Server> server(builder.BuildAndStart());
    std::cout << "🚀 [C++] Media Worker is LIVE at " << server_address << std::endl;

    // This keeps the program running so it doesn't immediately close
    server->Wait();
}

int main(int argc, char** argv) {
    RunServer();
    return 0;
}